Fix error with libxml-ruby 6.0.0
```
Finished in 0.050951s, 12600.3415 runs/s, 18586.4851 assertions/s.

  1) Error:
LoadParserCamelizeTest#test_load_parser_handles_underscore_names:
LoadError: cannot load such file -- libxml
    /Users/sue445/.rbenv/versions/4.0.2/lib/ruby/4.0.0/bundled_gems.rb:60:in 'Kernel.require'
    /Users/sue445/.rbenv/versions/4.0.2/lib/ruby/4.0.0/bundled_gems.rb:60:in 'block (2 levels) in Kernel#replace_require'
    lib/multi_xml/parsers/libxml_sax.rb:1:in '<top (required)>'
    /Users/sue445/.rbenv/versions/4.0.2/lib/ruby/4.0.0/bundled_gems.rb:60:in 'Kernel.require'
    /Users/sue445/.rbenv/versions/4.0.2/lib/ruby/4.0.0/bundled_gems.rb:60:in 'block (2 levels) in Kernel#replace_require'
    lib/multi_xml.rb:110:in 'MultiXml.load_parser'
    test/load_parser_test.rb:56:in 'LoadParserCamelizeTest#test_load_parser_handles_underscore_names'

642 runs, 947 assertions, 0 failures, 1 errors, 0 skips
```